export const EXAMPLES: string[] = ['Dashboard', 'Cards', 'Tasks', 'Playground', 'Music', 'Authentication'];

export const COMPONENTS = {
  Accordian: {},
  Alert: {},
  'Alert Dialog': {},
  'Aspect Ratio': {},
  Avatar: {},
  Badge: {},
  Button: {},
  Calendar: {},
  Card: {},
  Checkbox: {},
  Collapsible: {},
  'Combo Box': {},
  Command: {},
  'Context Manu': {},
  'Data Table': {},
  'Date Picker': {},
  Dialog: {},
  'Dropdown Menu': {},
  'Hover Card': {},
  Input: {},
  Label: {},
  'Menu Bar': {},
  'Navigation Menu': {},
  Popover: {},
  Progress: {},
  'Radio Group': {},
  'Scroll Area': {},
  Select: {},
  Separator: {},
  Sheet: {},
  Skeleton: {},
  Slider: {},
  Switch: {},
  Table: {},
  Tabs: {},
  Textarea: {},
  Toast: {},
  Toggle: {},
  Tooltip: {},
};
