export const EXAMPLES: string[] = ['Dashboard', 'Cards', 'Tasks', 'Playground', 'Music', 'Authentication'];

export const COMPONENTS: string[] = [
  'Accordian',
  'Alert',
  'Alert Dialog',
  'Aspect Ratio',
  'Avatar',
  'Badge',
  'Button',
  'Calendar',
  'Card',
  'Checkbox',
  'Collapsible',
  'Combobox',
  'Command',
  'Context Manu',
  'Data Table',
  'Date Picker',
  'Dialog',
  'Dropdown Menu',
  'Hover Card',
  'Input',
  'Label',
  'Menubar',
  'Navigation Menu',
  'Popover',
  'Progress',
  'Radio Group',
  'Scroll Area',
  'Select',
  'Separator',
  'Sheet',
  'Skeleton',
  'Slider',
  'Switch',
  'Table',
  'Tabs',
  'Textarea',
  'Toast',
  'Toggle',
  'Tooltip',
];
